media: src/assets
content:
  - name: posts
    label: Posts
    type: collection
    path: src/content/blog
    fields:
      - { name: title, label: Title, type: string } 
      - { name: author, label: Author, type: string } 
      - name: pubDatetime
        label: Publish Date
        type: date
        options:
          format: YYYY-MM-DD[T]HH:mm:ss[Z]
          time: true